### PR TITLE
Added travis ci support for modern node versions

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by abouthiroppy** [comment]
I think `v0.10` is unnecessary.
`v0.10` does not use in webpack.
https://github.com/webpack/webpack/blob/master/.travis.yml

**Comment by abouthiroppy** [comment]
LGTM 👍 
Can you please squash the commits?

**Comment by d3viant0ne** [comment]
@amilajack - As a general rule of thumb, loader support in regards to CI needs to be inline with webpack

**Comment by d3viant0ne** [comment]
@abouthiroppy - You can squash on merge

**Comment by d3viant0ne** [comment]
I am taking care of the rest of the tasks to get the CI up to webpack standards in #69

**Comment by hemanth** [comment]
@amilajack Would you please change the file as per @d3viant0ne [suggestion](https://github.com/webpack/html-loader/pull/66#issuecomment-234704923)?

**Pull request closed without merging**
