### PR TITLE
Revert "Add support for srcset"

### PR DESCRIPTION
**Pull request by hemanth**
@akesser reverting this, let us take this as a new feature altogether.

As @d3viant0ne pointed out, there are lot of edge cases for this to handle.

### CODE REVIEW

**Comment by duivvv** [comment]
what's the plan on this one? would be a nice addition

**Comment by maryo** [comment]
@hemanth @d3viant0ne Which edge cases? Is it listed somewhere? I couldn't find it :-/. This feature can be optional.

**Comment by mantastrunce** [comment]
@maryo an edge case might be that `srcset` doesn't generate correctly with a `publicPath` settings?

**Comment by thekip** [comment]
Want to open this discussion again, it's quite nice feature feature, otherwise I have to copy-paste code like that

```html
   <img
                 src="./assets/menu-screenshot.png"
                 srcset="./assets/menu-screenshot-2x.png 2x"
                 data-src="./assets/menu-screenshot-2x.png"
                 class="select-country-page__preview"/>
```

**Comment by AndreKR** [comment]
@maryo I have `"html-loader": "github:maryo/html-loader",` in my package.json. I'm using it with vue-loader. In my .vue component's template I have ``.

It should work like that? The problem might also be in vue-html-loader, I'm trying to find out where I should start looking.

**Comment by yawlhead91** [comment]
Any news with the srcset support

**Comment by evilebottnawi** [comment]
@yawlhead91 what about this https://github.com/herrstucki/responsive-loader?

**Pull request merged**
